// Generates placeholder KYC documents (clearly marked as samples) into the
// private local file store, so the admin review screen has files to open.
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const PRIVATE_ROOT = path.resolve("storage/private");

const TITLES: Record<string, string> = {
  TAX_REGISTRATION: "Tax Registration Certificate",
  BUSINESS_LICENSE: "Business Licence",
  GOVERNMENT_ID: "Government Identity Document",
  PROOF_OF_ADDRESS: "Proof of Business Address",
  BANK_STATEMENT: "Bank Statement",
  OTHER: "Supporting Document",
};

export async function writeSampleKycDocument(args: {
  key: string;
  type: string;
  legalName: string;
  holder: string;
  country: string;
  reference: string;
}) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const serif = await pdf.embedFont(StandardFonts.TimesRoman);
  const sans = await pdf.embedFont(StandardFonts.Helvetica);
  const ink = rgb(0.18, 0.17, 0.16);
  const muted = rgb(0.5, 0.48, 0.44);

  page.drawRectangle({ x: 40, y: 40, width: 515, height: 762, borderColor: rgb(0.82, 0.78, 0.72), borderWidth: 1 });
  page.drawText("SAMPLE — DEMONSTRATION DOCUMENT", { x: 60, y: 770, size: 9, font: sans, color: rgb(0.61, 0.31, 0.27) });
  page.drawText(TITLES[args.type] ?? "Document", { x: 60, y: 730, size: 24, font: serif, color: ink });

  const rows: [string, string][] = [
    ["Legal name", args.legalName],
    ["Account holder / director", args.holder],
    ["Country", args.country],
    ["Reference", args.reference],
    ["Issued", new Date().toISOString().slice(0, 10)],
  ];
  rows.forEach(([label, value], i) => {
    const y = 670 - i * 34;
    page.drawText(label.toUpperCase(), { x: 60, y, size: 8, font: sans, color: muted });
    page.drawText(value, { x: 60, y: y - 14, size: 12, font: serif, color: ink });
  });

  page.drawText(
    "This file was generated by the Loupe seed script to exercise the KYC review workflow. It is not an official record.",
    { x: 60, y: 120, size: 8, font: sans, color: muted, maxWidth: 470, lineHeight: 11 },
  );

  const bytes = await pdf.save();
  const filePath = path.join(PRIVATE_ROOT, args.key);
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, bytes);
  return bytes.byteLength;
}
